import { CheckCircle2, ChevronLeft, ChevronRight, Eye, Loader2, Plus, RefreshCw, Search, ShoppingBag, WalletCards, Clock3 } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useRealtime } from "../../hooks/useRealtime";
import { useSearchParams } from "react-router-dom";
import type { Order, OrderStatus, PaymentStatus } from "../../types/order";
import { getOrders } from "../../services/order.service";
import OrderFormModal from "../../components/orders/OrderFormModal";
import OrderDetailModal from "../../components/orders/OrderDetailModal";
import Toast from "../../components/ui/Toast";

type ToastType = "success" | "error" | "info";
const PAGE_SIZE = 10;
const STATUS_LABEL: Record<OrderStatus, string> = { RECEIVED:"Diterima", WASHING:"Dicuci", DRYING:"Dikeringkan", IRONING:"Disetrika", READY:"Siap Diambil", COMPLETED:"Selesai", CANCELLED:"Dibatalkan" };
const PAYMENT_LABEL: Record<PaymentStatus,string> = { UNPAID:"Belum Lunas", PARTIAL:"Sebagian", PAID:"Lunas", REFUNDED:"Dikembalikan" };
function money(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value)}
function date(value:string){return new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function statusClass(status:OrderStatus){return ({RECEIVED:"bg-slate-100 text-slate-700",WASHING:"bg-blue-50 text-blue-700",DRYING:"bg-sky-50 text-sky-700",IRONING:"bg-indigo-50 text-indigo-700",READY:"bg-emerald-50 text-emerald-700",COMPLETED:"bg-green-50 text-green-700",CANCELLED:"bg-red-50 text-red-700"})[status]}
function paymentClass(status:PaymentStatus){return ({UNPAID:"bg-slate-100 text-slate-600",PARTIAL:"bg-amber-50 text-amber-700",PAID:"bg-emerald-50 text-emerald-700",REFUNDED:"bg-red-50 text-red-700"})[status]}
function errorMessage(error:unknown){if(typeof error === "object"&&error!==null&&"response" in error)return (error as {response?:{data?:{message?:string}}}).response?.data?.message??"Gagal memuat data order.";return "Gagal memuat data order."}

const ORDER_EVENTS = ["order:created","order:updated","order:status-updated","order:deleted","payment:updated"] as const;

export default function OrdersPage(){
 const [searchParams] = useSearchParams();
 const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState<"ALL"|OrderStatus>("ALL"),[paymentFilter,setPaymentFilter]=useState<"ALL"|PaymentStatus>("ALL"),[page,setPage]=useState(1),[showForm,setShowForm]=useState(false),[selectedOrder,setSelectedOrder]=useState<Order|null>(null),[toast,setToast]=useState<{title:string;message:string;type:ToastType}|null>(null);
 useEffect(() => {
  const value = searchParams.get("search") ?? "";
  if (value) setSearch(value);
  if (searchParams.get("new") === "1") setShowForm(true);
 }, [searchParams]);
 async function loadOrders(silent=false){try{silent?setRefreshing(true):setLoading(true);setError("");setOrders(await getOrders())}catch(e){setError(errorMessage(e))}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void loadOrders()},[]); useRealtime(ORDER_EVENTS,()=>void loadOrders(true)); useEffect(()=>{setSelectedOrder(cur=>cur?(orders.find(o=>o.id===cur.id)??cur):cur)},[orders]); useEffect(()=>{setPage(1)},[search,statusFilter,paymentFilter]); useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),3800);return()=>window.clearTimeout(t)},[toast]);
 const filtered=useMemo(()=>{const k=search.trim().toLowerCase();return orders.filter(o=>{const match=!k||o.orderCode.toLowerCase().includes(k)||o.customer?.name.toLowerCase().includes(k)||o.customer?.phone.toLowerCase().includes(k);return match&&(statusFilter==="ALL"||o.status===statusFilter)&&(paymentFilter==="ALL"||o.paymentStatus===paymentFilter)})},[orders,search,statusFilter,paymentFilter]);
 const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),safePage=Math.min(page,pages),rows=filtered.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE);
 const paidCount=orders.filter(o=>o.paymentStatus==="PAID").length, unpaidCount=orders.filter(o=>o.paymentStatus!=="PAID"&&o.paymentStatus!=="REFUNDED").length, activeCount=orders.filter(o=>["RECEIVED","WASHING","DRYING","IRONING","READY"].includes(o.status)).length, totalValue=orders.reduce((s,o)=>s+Number(o.total),0);
 function created(order:Order){setOrders(c=>[order,...c.filter(x=>x.id!==order.id)]);setSelectedOrder(order);setToast({title:"Order berhasil dibuat",message:`${order.orderCode} ditambahkan ke antrean.`,type:"success"})}
 function updated(order:Order){setOrders(c=>c.map(x=>x.id===order.id?order:x));setSelectedOrder(order)}
 return <div className="page-enter space-y-7">
  {toast&&<Toast type={toast.type} title={toast.title} message={toast.message} onClose={()=>setToast(null)}/>} 
  <section className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1.5 text-[11px] font-black uppercase tracking-[.14em] text-[#185df9]"><ShoppingBag size={13}/> Order workspace</div><h1 className="text-3xl font-black tracking-[-.04em] text-slate-950 sm:text-4xl">Kelola semua order.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base">Pantau proses laundry, status pembayaran, dan detail pelanggan dari satu ruang kerja.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void loadOrders(true)} disabled={refreshing} title="Refresh" className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white p-3 text-slate-600 shadow-sm hover:border-blue-200 hover:text-blue-600"><RefreshCw size={16} className={refreshing?"animate-spin":""}/></button><button onClick={()=>setShowForm(true)} title="Buat order" className="inline-flex items-center justify-center rounded-2xl bg-[#185df9] p-3 text-white shadow-lg shadow-blue-500/20 hover:bg-blue-700"><Plus size={17}/></button></div></section>
  <section className="grid gap-4 grid-cols-2 lg:grid-cols-3 xl:grid-cols-5"><Kpi icon={ShoppingBag} label="Total order" value={orders.length.toString()} detail="Semua order tercatat"/><Kpi icon={Clock3} label="Sedang berjalan" value={activeCount.toString()} detail="Belum selesai" tone="blue"/><Kpi icon={CheckCircle2} label="Sudah paid" value={paidCount.toString()} detail="Order lunas" tone="green"/><Kpi icon={WalletCards} label="Belum lunas" value={unpaidCount.toString()} detail="Perlu ditindaklanjuti" tone="amber"/><Kpi icon={WalletCards} label="Nilai order" value={money(totalValue)} detail="Total nilai order" tone="dark"/></section>
  <section className="overflow-hidden rounded-[28px] border border-slate-200/80 bg-white shadow-[0_18px_60px_rgba(15,23,42,.06)]"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-center"><div className="relative min-w-0 flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari kode order, customer, atau nomor HP..." className="w-full rounded-2xl border border-slate-200 bg-slate-50 py-3.5 pl-11 pr-4 text-sm font-medium outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-500/10"/></div><div className="flex flex-wrap gap-2"><Filter value={statusFilter} onChange={v=>setStatusFilter(v as "ALL"|OrderStatus)} options={[["ALL","Semua status"],["RECEIVED","Diterima"],["WASHING","Dicuci"],["DRYING","Dikeringkan"],["IRONING","Disetrika"],["READY","Siap diambil"],["COMPLETED","Selesai"],["CANCELLED","Dibatalkan"]]}/><Filter value={paymentFilter} onChange={v=>setPaymentFilter(v as "ALL"|PaymentStatus)} options={[["ALL","Semua pembayaran"],["PAID","Lunas"],["PARTIAL","Sebagian"],["UNPAID","Belum lunas"],["REFUNDED","Refund"]]}/></div></div></div>
  {error?<div className="m-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>:loading?<div className="flex min-h-[380px] items-center justify-center"><Loader2 className="animate-spin text-[#185df9]" size={30}/></div>:rows.length===0?<div className="flex min-h-[380px] flex-col items-center justify-center p-8 text-center"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-slate-100 text-slate-400"><ShoppingBag/></div><h3 className="mt-5 text-lg font-black text-slate-900">Tidak ada order</h3><p className="mt-1 max-w-md text-sm text-slate-500">Coba ubah filter atau buat order baru.</p></div>:<>
   <div className="rtable-wrap overflow-x-auto p-3 sm:p-0"><table className="rtable orders-table w-full"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-left"><Th>Order</Th><Th>Customer</Th><Th>Service</Th><Th>Status</Th><Th>Pembayaran</Th><Th>Total</Th><Th>Dibuat</Th><Th>Aksi</Th></tr></thead><tbody>{rows.map(order=><tr key={order.id} className="group border-b border-slate-100 last:border-0 hover:bg-blue-50/30"><td data-label="Order" className="px-6 py-5"><p className="whitespace-nowrap text-[11px] font-black text-slate-900 sm:text-xs">{order.orderCode}</p></td><td data-label="Customer" className="px-6 py-5"><div><p className="text-sm font-bold text-slate-800">{order.customer?.name??"-"}</p><p className="mt-1 text-xs text-slate-400">{order.customer?.phone??"-"}</p></div></td><td data-label="Service" className="px-6 py-5"><div><p className="max-w-48 truncate text-sm font-semibold text-slate-700">{order.items?.map(i=>i.service?.name).filter(Boolean).join(", ")||"-"}</p><p className="mt-1 text-xs text-slate-400">{order.items?.length??0} layanan</p></div></td><td data-label="Status" className="px-6 py-5"><span className={`inline-flex rounded-full px-3 py-1.5 text-[11px] font-black ${statusClass(order.status)}`}>{STATUS_LABEL[order.status]}</span></td><td data-label="Pembayaran" className="px-6 py-5"><span className={`inline-flex rounded-full px-3 py-1.5 text-[11px] font-black ${paymentClass(order.paymentStatus)}`}>{PAYMENT_LABEL[order.paymentStatus]}</span></td><td data-label="Total" className="px-6 py-5"><p className="text-sm font-black text-slate-900">{money(Number(order.total))}</p></td><td data-label="Dibuat" className="px-6 py-5"><p className="whitespace-nowrap text-xs font-semibold text-slate-500">{date(order.createdAt)}</p></td><td data-label="Aksi" className="whitespace-nowrap px-4 py-5"><button onClick={()=>setSelectedOrder(order)} title="Detail" className="inline-flex shrink-0 items-center justify-center rounded-lg border border-slate-200 p-2 text-slate-600 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><Eye size={16}/></button></td></tr>)}</tbody></table></div>
   <div className="flex flex-col gap-3 border-t border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><p className="text-xs font-semibold text-slate-400">Menampilkan {rows.length} dari {filtered.length} order</p><div className="flex items-center gap-2"><button disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 disabled:opacity-40"><ChevronLeft size={16}/></button><span className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white">{safePage} / {pages}</span><button disabled={safePage>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 disabled:opacity-40"><ChevronRight size={16}/></button></div></div>
  </>}
  </section>
  <OrderFormModal open={showForm} onClose={()=>setShowForm(false)} onSaved={created} onToast={(message,type="info")=>setToast({title:type==="success"?"Berhasil":"Perhatian",message,type})}/>
  <OrderDetailModal open={!!selectedOrder} order={selectedOrder} onClose={()=>setSelectedOrder(null)} onUpdated={updated} onToast={(message,type="info")=>setToast({title:type==="success"?"Berhasil":type==="error"?"Gagal":"Informasi",message,type})}/>
 </div>
}
function Kpi({icon:Icon,label,value,detail,tone="default"}:{icon:typeof ShoppingBag;label:string;value:string;detail:string;tone?:"default"|"blue"|"green"|"amber"|"dark"}){const cls={default:"bg-white",blue:"bg-blue-50/70",green:"bg-emerald-50/70",amber:"bg-amber-50/70",dark:"bg-slate-950 text-white"}[tone];const icon=tone==="dark"?"bg-white/10 text-blue-300":"bg-slate-100 text-slate-600";return <div className={`rounded-[24px] border border-slate-200/80 p-5 shadow-sm ${cls}`}><div className="flex items-start justify-between gap-3"><div><p className={`text-[11px] font-black uppercase tracking-wider ${tone==="dark"?"text-slate-400":"text-slate-400"}`}>{label}</p><p className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{value}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${icon}`}><Icon size={18}/></div></div><p className={`mt-3 text-xs font-semibold ${tone==="dark"?"text-slate-400":"text-slate-400"}`}>{detail}</p></div>}
function Filter({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[][]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-xs font-bold text-slate-600 outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-500/10">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Th({children}:{children:ReactNode}){return <th className="px-6 py-4 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{children}</th>}
