import { useEffect, useMemo, useState } from "react";
import { useRealtime } from "../../hooks/useRealtime";
import { AlertCircle, ChevronLeft, ChevronRight, Eye, Loader2, Pencil, Plus, RefreshCw, Search, WashingMachine } from "lucide-react";
import { useAuth } from "../../contexts/AuthContext";
import { getMachines } from "../../services/machine.service";
import type { Machine, MachineStatus } from "../../types/machine";
import MachineDetailModal from "../../components/machines/MachineDetailModal";
import MachineFormModal from "../../components/machines/MachineFormModal";
import { formatCurrency, formatDate } from "../../utils/format";

const PAGE_SIZE = 10;
const STATUS_LABEL: Record<MachineStatus, string> = { ACTIVE: "Aktif", MAINTENANCE: "Maintenance", INACTIVE: "Nonaktif", BROKEN: "Rusak" };
function statusClass(status: MachineStatus) { if (status === "ACTIVE") return "bg-emerald-100 text-emerald-700"; if (status === "BROKEN") return "bg-red-100 text-red-700"; if (status === "MAINTENANCE") return "bg-amber-100 text-amber-700"; return "bg-slate-100 text-slate-700"; }
function errorMessage(error: unknown) { return (error as { response?: { data?: { message?: string } } }).response?.data?.message ?? "Data machine tidak dapat dimuat."; }

const MACHINE_EVENTS = ["data:changed:machines"] as const;

export default function MachinesPage() {
  const { user } = useAuth();
  const canEdit = user?.role === "ADMIN";
  const [machines, setMachines] = useState<Machine[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [status,setStatus]=useState<"ALL"|MachineStatus>("ALL"); const [page,setPage]=useState(1); const [selected,setSelected]=useState<Machine|null>(null); const [formOpen,setFormOpen]=useState(false); const [editing,setEditing]=useState<Machine|null>(null);
  async function load(silent = false) { try { if(!silent)setLoading(true); setError(""); setMachines(await getMachines()); } catch(err) { console.error(err); setError(errorMessage(err)); } finally { setLoading(false); } }
  useEffect(()=>{ void load(); },[]);
  useRealtime(MACHINE_EVENTS, () => void load(true)); useEffect(()=>{setPage(1)},[search,status]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase(); return machines.filter(m=>(!q||[m.machineCode,m.name,m.type,m.brand??"",m.model??"",m.serialNumber??"",m.location??""].some(v=>v.toLowerCase().includes(q)))&&(status==="ALL"||m.status===status));},[machines,search,status]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)); const safePage=Math.min(page,totalPages); const rows=filtered.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE);
  function handleSaved(machine:Machine){setMachines(current=>{const exists=current.some(x=>x.id===machine.id); return exists?current.map(x=>x.id===machine.id?machine:x):[machine,...current]}); setSelected(machine);}
  return <div className="page-enter space-y-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><p className="text-sm font-medium text-blue-600">Operational Management</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Machines</h1><p className="mt-1 text-sm text-slate-500">Kelola mesin laundry dan jadwal maintenance.</p></div>{canEdit&&<button type="button" title="Tambah Machine" onClick={()=>{setEditing(null);setFormOpen(true)}} className="inline-flex items-center justify-center rounded-xl bg-blue-600 p-3 text-white hover:bg-blue-700"><Plus size={18}/></button>}</div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Total Machine</p><p className="mt-2 text-2xl font-bold">{machines.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Aktif</p><p className="mt-2 text-2xl font-bold text-emerald-600">{machines.filter(x=>x.status==="ACTIVE").length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Maintenance</p><p className="mt-2 text-2xl font-bold text-amber-600">{machines.filter(x=>x.status==="MAINTENANCE").length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Rusak</p><p className="mt-2 text-2xl font-bold text-red-600">{machines.filter(x=>x.status==="BROKEN").length}</p></div></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-5 md:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-3.5 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari code, nama, tipe, brand, serial..." className="w-full rounded-xl border border-slate-300 py-3 pl-10 pr-4 text-sm outline-none focus:border-blue-500"/></div><select value={status} onChange={e=>setStatus(e.target.value as typeof status)} className="rounded-xl border border-slate-300 px-4 py-3 text-sm"><option value="ALL">Semua Status</option>{Object.entries(STATUS_LABEL).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button type="button" title="Refresh" onClick={()=>void load()} disabled={loading} className="inline-flex items-center justify-center rounded-xl border border-slate-300 p-3 text-slate-700 hover:bg-slate-50 disabled:opacity-50"><RefreshCw size={17} className={loading?"animate-spin":""}/></button></div>
      {loading?<div className="flex min-h-80 items-center justify-center gap-3 text-sm text-slate-500"><Loader2 size={24} className="animate-spin text-blue-600"/>Memuat machine...</div>:error?<div className="flex min-h-80 flex-col items-center justify-center text-center"><AlertCircle size={28} className="text-red-500"/><p className="mt-3 font-bold">Gagal memuat machine</p><p className="mt-1 text-sm text-slate-500">{error}</p><button type="button" onClick={()=>void load()} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Coba Lagi</button></div>:rows.length===0?<div className="flex min-h-80 flex-col items-center justify-center text-center"><WashingMachine size={32} className="text-slate-400"/><p className="mt-3 font-bold">Belum ada machine</p><p className="mt-1 text-sm text-slate-500">Tidak ada data yang sesuai dengan filter.</p></div>:
      <><div className="rtable-wrap overflow-x-auto p-3 sm:p-0"><table className="rtable w-full"><thead className="border-b border-slate-200 bg-slate-50"><tr>{["Machine","Tipe","Brand / Model","Lokasi","Maintenance","Status","Aksi"].map(t=><th key={t} className="px-5 py-4 text-left text-xs font-bold uppercase tracking-wide text-slate-500">{t}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(m=><tr key={m.id} className="hover:bg-slate-50"><td data-label="Machine" className="px-5 py-4"><div className="text-left"><p className="font-bold text-slate-900">{m.name}</p><p className="mt-1 text-xs text-slate-500">{m.machineCode} {m.serialNumber?`• ${m.serialNumber}`:""}</p></div></td><td data-label="Tipe" className="px-5 py-4 text-sm text-slate-600">{m.type}</td><td data-label="Brand / Model" className="px-5 py-4 text-sm text-slate-600">{m.brand||"-"}{m.model?` / ${m.model}`:""}</td><td data-label="Lokasi" className="px-5 py-4 text-sm text-slate-600">{m.location||"-"}</td><td data-label="Maintenance" className="px-5 py-4 text-sm text-slate-600"><div className="text-left sm:text-right"><p>Berikutnya: {m.nextMaintenanceAt?formatDate(m.nextMaintenanceAt):"-"}</p><p className="mt-1 text-xs text-slate-400">Biaya: {formatCurrency(Number(m.maintenanceCost||0))}</p></div></td><td data-label="Status" className="px-5 py-4"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${statusClass(m.status)}`}>{STATUS_LABEL[m.status]}</span></td><td data-label="Aksi" className="px-5 py-4"><div className="flex gap-2"><button type="button" title="Detail" onClick={()=>setSelected(m)} className="rounded-lg border border-slate-300 p-2 text-slate-600 hover:bg-slate-100"><Eye size={17}/></button>{canEdit&&<button type="button" title="Edit" onClick={()=>{setEditing(m);setFormOpen(true)}} className="rounded-lg border border-blue-200 p-2 text-blue-600 hover:bg-blue-50"><Pencil size={17}/></button>}</div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-200 px-5 py-4"><p className="text-sm text-slate-500">Menampilkan {filtered.length===0?0:(safePage-1)*PAGE_SIZE+1}-{Math.min(safePage*PAGE_SIZE,filtered.length)} dari {filtered.length}</p><div className="flex items-center gap-2"><button type="button" disabled={safePage===1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft size={18}/></button><span className="min-w-16 text-center text-sm font-semibold">{safePage} / {totalPages}</span><button type="button" disabled={safePage===totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight size={18}/></button></div></div></>}
    </div>
    <MachineFormModal open={formOpen} machine={editing} onClose={()=>setFormOpen(false)} onSaved={handleSaved}/><MachineDetailModal open={selected!==null} machine={selected} onClose={()=>setSelected(null)} onEdit={(m)=>{setSelected(null);setEditing(m);setFormOpen(true)}}/>
  </div>;
}
