import { useEffect, useState } from "react";
import { Loader2, MapPin, Settings, X } from "lucide-react";
import { getMachineById } from "../../services/machine.service";
import type { Machine } from "../../types/machine";
import { formatCurrency, formatDate } from "../../utils/format";

type Props = { open: boolean; machine: Machine | null; onClose: () => void; onEdit: (machine: Machine) => void };
function statusClass(status: Machine["status"]) { if (status === "ACTIVE") return "bg-emerald-100 text-emerald-700"; if (status === "BROKEN") return "bg-red-100 text-red-700"; if (status === "MAINTENANCE") return "bg-amber-100 text-amber-700"; return "bg-slate-100 text-slate-700"; }
export default function MachineDetailModal({ open, machine, onClose, onEdit }: Props) {
  const [detail, setDetail] = useState<Machine | null>(machine); const [loading, setLoading] = useState(false);
  useEffect(() => { setDetail(machine); if (!open || !machine?.id) return; void (async()=>{ try { setLoading(true); setDetail(await getMachineById(machine.id)); } finally { setLoading(false); } })(); }, [open, machine]);
  if (!open || !detail) return null;
  return <div className="fixed inset-0 z-80 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl">
    <div className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Machine Detail</p><h2 className="mt-1 text-xl font-bold text-slate-900">{detail.name}</h2><p className="mt-1 text-sm text-slate-500">{detail.machineCode}</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={20}/></button></div>
    <div className="space-y-5 p-6">{loading && <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 size={17} className="animate-spin"/>Memuat detail...</div>}
      <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Status</p><span className={`mt-2 inline-flex rounded-full px-3 py-1 text-xs font-bold ${statusClass(detail.status)}`}>{detail.status}</span></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Tipe</p><p className="mt-1 font-bold">{detail.type}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Lokasi</p><p className="mt-1 flex items-center gap-1 font-bold"><MapPin size={15}/>{detail.location || "-"}</p></div></div>
      <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Informasi Machine</h3><div className="mt-4 space-y-3 text-sm text-slate-600"><p>Brand: <b className="text-slate-900">{detail.brand || "-"}</b></p><p>Model: <b className="text-slate-900">{detail.model || "-"}</b></p><p>Serial Number: <b className="text-slate-900">{detail.serialNumber || "-"}</b></p><p>Tanggal Pembelian: <b className="text-slate-900">{detail.purchaseDate ? formatDate(detail.purchaseDate) : "-"}</b></p><p>Harga Pembelian: <b className="text-slate-900">{detail.purchasePrice == null ? "-" : formatCurrency(Number(detail.purchasePrice))}</b></p></div></div><div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Maintenance</h3><div className="mt-4 space-y-3 text-sm text-slate-600"><p>Terakhir: <b className="text-slate-900">{detail.lastMaintenanceAt ? formatDate(detail.lastMaintenanceAt) : "-"}</b></p><p>Berikutnya: <b className="text-slate-900">{detail.nextMaintenanceAt ? formatDate(detail.nextMaintenanceAt) : "-"}</b></p><p>Biaya: <b className="text-slate-900">{formatCurrency(Number(detail.maintenanceCost || 0))}</b></p></div></div></div>
      {detail.maintenanceNotes && <div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-800"><b>Catatan:</b> {detail.maintenanceNotes}</div>}
      <div className="flex justify-end gap-3 border-t border-slate-200 pt-5"><button type="button" onClick={onClose} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">Tutup</button><button type="button" onClick={()=>onEdit(detail)} title="Edit Machine" className="inline-flex items-center justify-center rounded-xl bg-blue-600 p-3 text-white"><Settings size={17}/></button></div>
    </div></div></div>;
}
