import { useEffect, useMemo, useState } from "react";
import { Eye, History, Package, Pencil, Plus, RefreshCw, Search, XCircle } from "lucide-react";
import type { InventoryItem, InventoryTransaction } from "../../types/inventory";
import { getInventoryItems, getInventoryTransactions, updateInventoryItem } from "../../services/inventory.service";
import { useAuth } from "../../contexts/AuthContext";
import InventoryFormModal from "../../components/inventory/InventoryFormModal";
import StockTransactionModal from "../../components/inventory/StockTransactionModal";
import { formatCurrency, formatDate } from "../../utils/format";
import Toast, { type ToastType } from "../../components/ui/Toast";

type ToastState={type:ToastType;title:string;message:string};

export default function InventoryPage(){
 const {user}=useAuth();
 const [items,setItems]=useState<InventoryItem[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState("");
 const [status,setStatus]=useState<"ALL"|"ACTIVE"|"INACTIVE"|"LOW">("ALL"); const [page,setPage]=useState(1); const [formOpen,setFormOpen]=useState(false); const [editing,setEditing]=useState<InventoryItem|null>(null);
 const [transactionItem,setTransactionItem]=useState<InventoryItem|null>(null); const [historyItem,setHistoryItem]=useState<InventoryItem|null>(null); const [history,setHistory]=useState<InventoryTransaction[]>([]); const [historyLoading,setHistoryLoading]=useState(false); const [toast,setToast]=useState<ToastState|null>(null); const pageSize=10;
 async function load(){try{setLoading(true);setItems(await getInventoryItems())}catch(e){console.error(e);setToast({type:"error",title:"Gagal memuat inventory",message:"Data inventory tidak dapat diambil dari server."})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]); useEffect(()=>{setPage(1)},[search,status]); useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),4000);return()=>window.clearTimeout(t)},[toast]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(i=>{const match=!q||i.name.toLowerCase().includes(q)||i.sku.toLowerCase().includes(q)||(i.category??"").toLowerCase().includes(q);const low=Number(i.currentStock)<=Number(i.minimumStock);const st=status==="ALL"||(status==="ACTIVE"&&i.isActive)||(status==="INACTIVE"&&!i.isActive)||(status==="LOW"&&low);return match&&st})},[items,search,status]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)); const safePage=Math.min(page,totalPages); const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 const lowCount=items.filter(i=>Number(i.currentStock)<=Number(i.minimumStock)&&i.isActive).length; const activeCount=items.filter(i=>i.isActive).length;
 function saved(item:InventoryItem,mode:"create"|"update"){setItems(c=>mode==="update"?c.map(x=>x.id===item.id?item:x):[item,...c]);setFormOpen(false);setEditing(null);setToast({type:"success",title:mode==="create"?"Inventory ditambahkan":"Inventory diperbarui",message:"Data berhasil disimpan."})}
 async function openHistory(item:InventoryItem){setHistoryItem(item);setHistoryLoading(true);try{setHistory(await getInventoryTransactions(item.id))}catch(e){console.error(e);setToast({type:"error",title:"Gagal memuat riwayat",message:"Riwayat transaksi tidak dapat diambil."})}finally{setHistoryLoading(false)}}
 async function toggle(item:InventoryItem){if(!window.confirm(`${item.isActive?"Nonaktifkan":"Aktifkan"} inventory ${item.name}?`)) return;try{const updated=await updateInventoryItem(item.id,{isActive:!item.isActive});setItems(c=>c.map(x=>x.id===updated.id?updated:x));setToast({type:"success",title:updated.isActive?"Inventory diaktifkan":"Inventory dinonaktifkan",message:"Status inventory berhasil diperbarui."})}catch(e){console.error(e);setToast({type:"error",title:"Gagal mengubah status",message:"Status inventory gagal diperbarui."})}}
 return <div className="page-enter space-y-6">
  <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-blue-600">Inventory</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Manajemen Inventory</h1><p className="mt-1 text-sm text-slate-500">Kelola bahan, stok, supplier, dan transaksi stok.</p></div>{user?.role==="ADMIN"&&<button onClick={()=>{setEditing(null);setFormOpen(true)}} title="Tambah Inventory" className="inline-flex items-center justify-center rounded-xl bg-blue-600 p-3 text-white hover:bg-blue-700"><Plus size={18}/></button>}</section>
  <section className="grid gap-4 sm:grid-cols-3"><Stat label="Total Item" value={items.length} icon={Package}/><Stat label="Item Aktif" value={activeCount} icon={Package}/><Stat label="Stok Menipis" value={lowCount} icon={XCircle}/></section>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari SKU, nama, kategori..." className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-blue-500"/></div><select value={status} onChange={e=>setStatus(e.target.value as typeof status)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm"><option value="ALL">Semua</option><option value="ACTIVE">Aktif</option><option value="INACTIVE">Nonaktif</option><option value="LOW">Stok Menipis</option></select><button onClick={()=>void load()} title="Refresh" className="inline-flex items-center justify-center rounded-xl border border-slate-200 p-2.5 text-slate-600 hover:bg-slate-50"><RefreshCw size={16}/></button></div>
   <div className="rtable-wrap overflow-x-auto p-3 sm:p-0"><table className="rtable w-full text-left"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Item</th><th className="px-5 py-3">Kategori</th><th className="px-5 py-3">Stok</th><th className="px-5 py-3">Harga Modal</th><th className="px-5 py-3">Supplier</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={7} className="px-5 py-12 text-center text-sm text-slate-500">Memuat data...</td></tr>:visible.length===0?<tr><td colSpan={7} className="px-5 py-12 text-center text-sm text-slate-500">Tidak ada data inventory.</td></tr>:visible.map(item=>{const low=Number(item.currentStock)<=Number(item.minimumStock);return <tr key={item.id} className="hover:bg-slate-50/70"><td data-label="Item" className="px-5 py-4"><div className="text-left"><p className="font-semibold text-slate-900">{item.name}</p><p className="text-xs text-slate-400">{item.sku}</p></div></td><td data-label="Kategori" className="px-5 py-4 text-sm text-slate-600">{item.category||"-"}</td><td data-label="Stok" className="px-5 py-4"><div className="text-left sm:text-right"><p className={`font-semibold ${low?"text-red-600":"text-slate-900"}`}>{Number(item.currentStock)} {item.unit}</p><p className="text-xs text-slate-400">Min. {Number(item.minimumStock)}</p></div></td><td data-label="Harga Modal" className="px-5 py-4 text-sm text-slate-600">{formatCurrency(Number(item.costPrice))}</td><td data-label="Supplier" className="px-5 py-4 text-sm text-slate-600">{item.supplierName||"-"}</td><td data-label="Status" className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${!item.isActive?"bg-slate-100 text-slate-500":low?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{!item.isActive?"Nonaktif":low?"Stok Menipis":"Aktif"}</span></td><td data-label="Aksi" className="px-5 py-4"><div className="flex justify-end gap-2"><button title="Transaksi stok" onClick={()=>setTransactionItem(item)} className="rounded-lg border border-blue-100 p-2 text-blue-600 hover:bg-blue-50"><Plus size={16}/></button><button title="Riwayat" onClick={()=>void openHistory(item)} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"><History size={16}/></button>{user?.role==="ADMIN"&&<><button title="Edit" onClick={()=>{setEditing(item);setFormOpen(true)}} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"><Pencil size={16}/></button><button title={item.isActive?"Nonaktifkan":"Aktifkan"} onClick={()=>void toggle(item)} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"><Eye size={16}/></button></>}</div></td></tr>})}</tbody></table></div>
   <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4"><p className="text-sm text-slate-500">Menampilkan {filtered.length===0?0:(safePage-1)*pageSize+1}–{Math.min(safePage*pageSize,filtered.length)} dari {filtered.length}</p><div className="flex gap-2"><button disabled={safePage<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-40">Sebelumnya</button><span className="px-2 py-2 text-sm text-slate-500">{safePage}/{totalPages}</span><button disabled={safePage>=totalPages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-40">Berikutnya</button></div></div>
  </section>
  {formOpen&&<InventoryFormModal item={editing} onClose={()=>{setFormOpen(false);setEditing(null)}} onSaved={saved}/>} {transactionItem&&<StockTransactionModal item={transactionItem} onClose={()=>setTransactionItem(null)} onSaved={item=>{setItems(c=>c.map(x=>x.id===item.id?item:x));setTransactionItem(null);setToast({type:"success",title:"Transaksi berhasil",message:"Stok inventory berhasil diperbarui."} as ToastState)}}/>}
  {historyItem&&<HistoryModal item={historyItem} transactions={history} loading={historyLoading} onClose={()=>setHistoryItem(null)}/>} {toast&&<Toast {...toast} onClose={() => setToast(null)}/>}</div>
}
function Stat({label,value,icon:Icon}:{label:string;value:number;icon:typeof Package}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={21}/></div></div></div>}
function HistoryModal({item,transactions,loading,onClose}:{item:InventoryItem;transactions:InventoryTransaction[];loading:boolean;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[85vh] w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><h2 className="font-bold text-slate-900">Riwayat Stok</h2><p className="text-sm text-slate-500">{item.name} · {item.sku}</p></div><button onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100">×</button></div><div className="max-h-[65vh] overflow-auto p-6">{loading?<p className="py-10 text-center text-sm text-slate-500">Memuat riwayat...</p>:transactions.length===0?<p className="py-10 text-center text-sm text-slate-500">Belum ada transaksi.</p>:<div className="space-y-3">{transactions.map(t=><div key={t.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{t.type}</span><p className="mt-2 text-sm font-semibold text-slate-800">{formatDate(t.createdAt)} · {t.createdBy?.name??"-"}</p></div><p className="text-lg font-bold text-slate-900">{Number(t.quantity)} {item.unit}</p></div><div className="mt-3 flex gap-6 text-xs text-slate-500"><span>Sebelum: {Number(t.stockBefore)}</span><span>Sesudah: {Number(t.stockAfter)}</span></div>{t.note&&<p className="mt-2 text-sm text-slate-500">{t.note}</p>}</div>)}</div>}</div></div></div>}
