import { useCallback, useState } from "react";
import { RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import MetricCard from "../components/MetricCard";
import OrderCard from "../components/OrderCard";
import { getDashboardSummary, getRecentOrders } from "../services/dashboard.service";
import type { DashboardSummary, Order } from "../types/api";
import { colors } from "../theme/colors";

export default function HomeScreen({ navigation }: any) {
  const [summary, setSummary] = useState<DashboardSummary | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { try { const [s, o] = await Promise.all([getDashboardSummary(), getRecentOrders(5)]); setSummary(s); setOrders(o); } catch {} }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  async function refresh() { setRefreshing(true); await load(); setRefreshing(false); }
  const money = (n: number) => `Rp ${Number(n).toLocaleString("id-ID")}`;
  return <ScrollView style={styles.root} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.brand} />}>
    <View style={styles.header}><Text style={styles.eyebrow}>LAUNDRIFY OPERATIONS</Text><Text style={styles.title}>Good morning, Admin 👋</Text><Text style={styles.subtitle}>Ringkasan operasional hari ini.</Text></View>
    <View style={styles.grid}><MetricCard label="Revenue Today" value={money(summary?.today.revenue ?? 0)} icon="↗" /><MetricCard label="Orders Today" value={String(summary?.today.orders ?? 0)} icon="▣" accent="#7C3AED" /></View>
    <View style={styles.grid}><MetricCard label="Paid Orders" value={String(summary?.lifetime.paidOrders ?? 0)} icon="✓" accent={colors.success} /><MetricCard label="Members" value={String(summary?.customers.members ?? 0)} icon="♙" accent={colors.warning} /></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Revenue & Profit</Text><Text style={styles.big}>{money(summary?.today.profit ?? 0)}</Text><Text style={styles.muted}>Profit hari ini</Text><View style={styles.chart}><View style={[styles.bar, { height: "45%" }]} /><View style={[styles.bar, { height: "72%" }]} /><View style={[styles.bar, { height: "58%" }]} /><View style={[styles.bar, { height: "88%" }]} /><View style={[styles.bar, { height: "65%" }]} /><View style={[styles.bar, { height: "95%" }]} /></View></View>
    <View style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>Order Status</Text><Text style={styles.muted}>This month</Text></View><Status label="Pending" value={summary?.orderStatus.pending ?? 0} color={colors.warning} /><Status label="Completed" value={summary?.orderStatus.completed ?? 0} color={colors.success} /><Status label="Cancelled" value={summary?.orderStatus.cancelled ?? 0} color={colors.danger} /></View>
    <View style={styles.lifetime}><Text style={styles.lifetimeLabel}>LIFETIME REVENUE</Text><Text style={styles.lifetimeValue}>{money(summary?.lifetime.revenue ?? 0)}</Text><Text style={styles.lifetimeText}>Akumulasi pembayaran berhasil sejak laundry dibuka.</Text></View>
    <View style={[styles.row, { marginBottom: 12 }]}><Text style={styles.sectionTitle}>Recent Orders</Text><Text style={styles.link}>History</Text></View>
    {orders.map(order => <OrderCard key={order.id} order={order} onPress={() => navigation.navigate("OrderDetail", { orderId: order.id })} />)}
  </ScrollView>;
}
function Status({ label, value, color }: { label: string; value: number; color: string }) { return <View style={styles.status}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={styles.statusLabel}>{label}</Text><Text style={styles.statusValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.slate50 }, content: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 112 }, header: { marginBottom: 20 }, eyebrow: { color: colors.brand, fontSize: 10, fontWeight: "900", letterSpacing: 1.4 }, title: { color: colors.navy, fontSize: 26, fontWeight: "800", marginTop: 5 }, subtitle: { color: colors.slate500, fontSize: 13, marginTop: 5 }, grid: { flexDirection: "row", gap: 12, marginBottom: 12 }, card: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.slate200, borderRadius: 20, padding: 18, marginBottom: 14 }, cardTitle: { color: colors.navy, fontSize: 15, fontWeight: "800" }, big: { color: colors.navy, fontSize: 28, fontWeight: "900", marginTop: 10 }, muted: { color: colors.slate500, fontSize: 11 }, chart: { height: 100, flexDirection: "row", alignItems: "flex-end", gap: 10, marginTop: 18, borderBottomWidth: 1, borderBottomColor: colors.slate200, paddingHorizontal: 4 }, bar: { flex: 1, backgroundColor: colors.brand, borderTopLeftRadius: 7, borderTopRightRadius: 7 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, status: { flexDirection: "row", alignItems: "center", paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.slate100 }, dot: { width: 9, height: 9, borderRadius: 5, marginRight: 10 }, statusLabel: { color: colors.slate600, fontWeight: "600", flex: 1 }, statusValue: { color: colors.navy, fontWeight: "800" }, lifetime: { backgroundColor: colors.navy, borderRadius: 22, padding: 22, marginBottom: 22 }, lifetimeLabel: { color: "#7DD3FC", fontSize: 10, fontWeight: "900", letterSpacing: 1.3 }, lifetimeValue: { color: colors.white, fontSize: 30, fontWeight: "900", marginTop: 8 }, lifetimeText: { color: "#CBD5E1", fontSize: 12, marginTop: 6 }, sectionTitle: { color: colors.navy, fontSize: 18, fontWeight: "900" }, link: { color: colors.brand, fontSize: 12, fontWeight: "800" } });
