import { ArrowUpRight, Boxes, Cog, Package, Tags, Truck, WashingMachine } from "lucide-react";
import { Link } from "react-router-dom";

const modules = [
  { title: "Services", text: "Kelola paket layanan, harga, dan penggunaan inventory.", path: "/operations/services", icon: Tags, tag: "Master data" },
  { title: "Inventory", text: "Pantau stok bahan, transaksi, supplier, dan stok minimum.", path: "/operations/inventory", icon: Package, tag: "Stock control" },
  { title: "Deliveries", text: "Atur pickup, pengantaran, courier, dan status perjalanan.", path: "/operations/deliveries", icon: Truck, tag: "Logistics" },
  { title: "Machines", text: "Monitor mesin, status operasional, dan maintenance.", path: "/operations/machines", icon: WashingMachine, tag: "Assets" },
] as const;

export default function OperationsPage(){return <div className="page-enter space-y-6"><header><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-cyan-50 px-3 py-1.5 text-[11px] font-black uppercase tracking-wider text-cyan-700"><Cog size={13}/> Operations center</div><h1 className="text-3xl font-black tracking-[-0.04em] text-slate-950 sm:text-4xl">Operasional</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Semua pekerjaan yang membuat proses laundry berjalan berada dalam satu workspace.</p></header><div className="grid gap-5 md:grid-cols-2">{modules.map(({title,text,path,icon:Icon,tag},i)=><Link key={path} to={path} className="group relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-slate-300 hover:shadow-xl"><div className={`absolute -right-12 -top-12 h-32 w-32 rounded-full ${i%2===0?"bg-cyan-50":"bg-blue-50"} transition group-hover:scale-125`}/><div className="relative"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-white shadow-lg"><Icon size={20}/></div><ArrowUpRight size={19} className="text-slate-300 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-slate-900"/></div><span className="mt-7 inline-flex rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-slate-500">{tag}</span><h2 className="mt-3 text-xl font-black text-slate-950">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p><div className="mt-6 inline-flex items-center gap-2 text-xs font-black text-slate-950">Buka modul <ArrowUpRight size={14}/></div></div></Link>)}</div><div className="rounded-[28px] bg-slate-950 p-6 text-white sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-blue-300"><Boxes size={17}/><span className="text-xs font-black uppercase tracking-wider">Operational workspace</span></div><h2 className="mt-2 text-xl font-black">Satu tempat untuk proses harian.</h2><p className="mt-1 text-sm text-slate-400">Gunakan modul di atas sesuai kebutuhan pekerjaan Anda.</p></div><Link to="/orders" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-4 py-3 text-xs font-black text-slate-950 hover:bg-blue-100">Lihat Orders <ArrowUpRight size={15}/></Link></div></div></div>}
