import { ArrowUpRight, BarChart3, CircleDollarSign, ReceiptText, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { getDashboardSummary } from "../../services/dashboard.service";
import type { DashboardSummary } from "../../types/dashboard";
import { formatCurrency } from "../../utils/format";

export default function FinancePage(){const [data,setData]=useState<DashboardSummary|null>(null);useEffect(()=>{void getDashboardSummary().then(setData).catch(console.error)},[]);return <div className="page-enter space-y-6"><header><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-[11px] font-black uppercase tracking-wider text-emerald-700"><CircleDollarSign size={13}/> Finance center</div><h1 className="text-3xl font-black tracking-[-0.04em] text-slate-950 sm:text-4xl">Keuangan</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Ringkasan arus uang Laundrify dan pengelolaan pengeluaran operasional.</p></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><FinanceCard label="Revenue Hari Ini" value={data?formatCurrency(data.today.revenue):"—"} icon={CircleDollarSign}/><FinanceCard label="Expense Hari Ini" value={data?formatCurrency(data.today.expense):"—"} icon={ReceiptText}/><FinanceCard label="Profit Hari Ini" value={data?formatCurrency(data.today.profit):"—"} icon={BarChart3}/><FinanceCard label="Order Hari Ini" value={data?String(data.today.orders):"—"} icon={WalletCards}/></div><div className="grid gap-5 lg:grid-cols-2"><Link to="/orders" className="group rounded-[28px] bg-slate-950 p-7 text-white shadow-xl transition hover:-translate-y-1"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><CircleDollarSign size={21}/></div><ArrowUpRight className="text-slate-500 transition group-hover:text-white"/></div><h2 className="mt-8 text-xl font-black">Payment melalui Orders</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-400">Pembayaran tidak lagi menjadi menu terpisah. Buka detail order untuk melihat tagihan dan mencatat pembayaran.</p></Link><Link to="/finance/expenses" className="group rounded-[28px] border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-50 text-amber-700"><ReceiptText size={21}/></div><ArrowUpRight className="text-slate-300 transition group-hover:text-slate-900"/></div><h2 className="mt-8 text-xl font-black text-slate-950">Expenses</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Catat listrik, air, perlengkapan, maintenance, delivery, dan pengeluaran lainnya.</p></Link></div><div className="rounded-[28px] border border-slate-200 bg-white p-6"><div className="flex items-start gap-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-700"><BarChart3 size={19}/></div><div><h2 className="font-black text-slate-950">Catatan arsitektur</h2><p className="mt-1 text-sm leading-6 text-slate-500">Menu Finance menjadi pusat ringkasan keuangan. Detail transaksi pembayaran tetap berada pada Order, sedangkan pengeluaran dikelola di Expenses.</p></div></div></div></div>}
function FinanceCard({label,value,icon:Icon}:{label:string;value:string;icon:typeof CircleDollarSign}){return <div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-black text-slate-950">{value}</p></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 text-slate-700"><Icon size={19}/></div></div></div>}
